// frontend/src/components/Footer.tsx
import React from 'react';
import { Container, Group, Text, Anchor, Paper } from '@mantine/core';
import DiagnosticsBadge from './dev/DiagnosticsBadge';
import { useThemeMode, getThemeColors } from '../theme';
import { useTranslation } from 'react-i18next';

const Footer: React.FC = () => {
  const year = new Date().getFullYear();
  const { t } = useTranslation();
  const { colorScheme } = useThemeMode();
  const colors = getThemeColors(colorScheme);

  return (
    <Paper component="footer" radius={0} p="md" withBorder={false} style={{ backgroundColor: colors.background.primary, borderTop: `1px solid ${colors.ui.border}` }}>
      <Container>
        <Group justify="space-between" align="center">
          <Text size="sm" c="dimmed">
            © {year} Scoracle. {t('footer.allRightsReserved')}
          </Text>
          <Group>
            <Anchor href="#" target="_blank" c="dimmed" size="sm">
              {t('footer.terms')}
            </Anchor>
            <Anchor href="#" target="_blank" c="dimmed" size="sm">
              {t('footer.privacy')}
            </Anchor>
            <DiagnosticsBadge />
          </Group>
        </Group>
      </Container>
    </Paper>
  );
};

export default Footer;

// scoracle-svelte/src/lib/components/Footer.svelte
<script lang="ts">
  /**
   * Footer component
   * Migrated from React Footer.tsx
   */
  import { _ } from 'svelte-i18n';
  import { colorScheme, getThemeColors } from '$lib/stores/theme';

  $: colors = getThemeColors($colorScheme);
  $: year = new Date().getFullYear();
</script>

<footer
  class="mt-auto py-6 border-t"
  style="background-color: {colors.background.primary}; border-color: {colors.ui.border};"
>
  <div class="container mx-auto px-4">
    <div class="flex flex-col md:flex-row items-center justify-between gap-4">
      <!-- Copyright -->
      <p class="text-sm" style="color: {colors.text.secondary};">
        © {year} Scoracle. {$_('footer.allRightsReserved')}
      </p>

      <!-- Links -->
      <div class="flex items-center gap-6">
        <a
          href="/terms"
          class="text-sm hover:underline transition-colors"
          style="color: {colors.text.secondary};"
        >
          {$_('footer.terms')}
        </a>
        <a
          href="/privacy"
          class="text-sm hover:underline transition-colors"
          style="color: {colors.text.secondary};"
        >
          {$_('footer.privacy')}
        </a>
      </div>
    </div>
  </div>
</footer>
