// frontend/src/components/Header.tsx
import React, { useState } from 'react';
import './Header.css';
import { Link } from 'react-router-dom';
import { Group, Box, Paper, ActionIcon, Drawer, Switch, Select, Stack, Text, Tooltip } from '@mantine/core';
import { IconMenu2 } from '@tabler/icons-react';
import { useThemeMode, getThemeColors } from '../theme';
import { useLanguage } from '../context/LanguageContext';
import { useTranslation } from 'react-i18next';

const Header: React.FC = () => {
  const { language, changeLanguage, languages } = useLanguage() as {
    language: string;
    changeLanguage: (lang: string) => void;
    languages: Array<{ id: string; display: string; label: string }>;
  };
  const { colorScheme, toggleColorScheme } = useThemeMode();
  const isDark = colorScheme === 'dark';
  const { t } = useTranslation();
  const [settingsOpen, setSettingsOpen] = useState(false);

  // Get appropriate header colors based on color scheme
  const colors = getThemeColors(colorScheme);

  const headerStyle: React.CSSProperties = {
    background: colors.background.primary,
    borderBottom: colorScheme === 'light' 
      ? `1px solid #D0D5DC` 
      : `1px solid ${colors.ui.border}`,
    padding: '0.5rem 0',
  };

  return (
    <Paper component="header" shadow="none" radius={0} p={0} style={{ ...headerStyle, position: 'relative' }}>
      <Box style={{ display: 'flex', alignItems: 'center', height: '60px', justifyContent: 'center', position: 'relative', width: '100%' }}>
        {/* Left: Hamburger -> settings drawer */}
        <Group style={{ position: 'absolute', left: '1rem', top: '50%', transform: 'translateY(-50%)', zIndex: 1 }}>
          <Tooltip label={t('header.menu')} withArrow>
            <ActionIcon variant="subtle" color="gray" aria-label="Open menu" onClick={() => setSettingsOpen(true)}>
              <IconMenu2 size={22} color={colors.text.primary} />
            </ActionIcon>
          </Tooltip>
        </Group>

        {/* Center: Brand/logo -> home */}
        <Box style={{ display: 'flex', alignItems: 'center' }}>
          <Link to="/" aria-label="Go to home" style={{ textDecoration: 'none' }}>
            <img src="/scoracle-logo.png" alt="Scoracle" className="header-logo" />
          </Link>
        </Box>

        {/* Right: Language selector */}
        <Group style={{ position: 'absolute', right: '1rem', top: '50%', transform: 'translateY(-50%)', zIndex: 1 }}>
          <Select
            aria-label={t('header.language') || 'Select language'}
            data={languages.map((l) => ({ value: l.id, label: l.id.toUpperCase() }))}
            value={language}
            onChange={(v) => v && changeLanguage(v || language)}
            size="xs"
            styles={{ 
              input: { 
                background: 'transparent', 
                color: colors.text.primary, 
                borderColor: colorScheme === 'light' ? '#D0D5DC' : colors.ui.border,
                width: '60px',
                minWidth: '60px',
                maxWidth: '60px'
              },
              wrapper: {
                width: '60px',
                minWidth: '60px',
                maxWidth: '60px'
              },
              dropdown: {
                backgroundColor: colors.background.secondary,
              },
              option: {
                backgroundColor: colors.background.secondary,
                '&:hover': {
                  backgroundColor: colors.background.tertiary,
                }
              }
            }}
          />
        </Group>
      </Box>

      {/* Settings Drawer - light/dark only for now */}
      <Drawer 
        opened={settingsOpen} 
        onClose={() => setSettingsOpen(false)} 
        title={t('header.settings')} 
        position="left"
        styles={{
          content: {
            backgroundColor: colors.background.secondary,
          },
          body: {
            backgroundColor: colors.background.secondary,
          },
          header: {
            backgroundColor: colors.background.secondary,
          },
          title: {
            color: colors.text.primary,
          }
        }}
      >
        <Stack>
          <Text fw={600}>{t('header.appearance')}</Text>
          <Switch checked={isDark} onChange={toggleColorScheme} label={t('header.darkMode')} />
        </Stack>
      </Drawer>
    </Paper>
  );
};

export default Header;

// scoracle-svelte/src/lib/components/Header.svelte
<script lang="ts">
  /**
   * Header component - site header with navigation and settings
   * Migrated from React Header.tsx
   */
  import { _ } from 'svelte-i18n';
  import { IconMenu2, IconX, IconSun, IconMoon } from '@tabler/icons-svelte';
  import { colorScheme, isDark, getThemeColors } from '$lib/stores/theme';
  import { languages, changeLanguage, locale } from '$lib/stores/language';

  let settingsOpen = $state(false);
  let colors = $derived(getThemeColors($colorScheme));

  function toggleSettings() {
    settingsOpen = !settingsOpen;
  }

  function closeSettings() {
    settingsOpen = false;
  }

  function handleLanguageChange(event: Event) {
    const select = event.target as HTMLSelectElement;
    changeLanguage(select.value);
  }
</script>

<header
  class="sticky top-0 z-50 h-16 border-b transition-colors"
  style="background-color: {colors.background.primary}; border-color: {colors.ui.border};"
>
  <div class="container mx-auto h-full flex items-center justify-between px-4 relative">
    <!-- Left: Hamburger menu -->
    <button
      class="p-2 rounded-lg hover:bg-surface-200 dark:hover:bg-surface-700 transition-colors"
      onclick={toggleSettings}
      aria-label={$_('header.menu')}
    >
      <IconMenu2 size={22} style="color: {colors.text.primary}" />
    </button>

    <!-- Center: Logo -->
    <a href="/" class="absolute left-1/2 -translate-x-1/2 flex items-center">
      <img src="/scoracle-logo.png" alt="Scoracle" class="h-10" />
    </a>

    <!-- Right: Language selector -->
    <select
      class="px-2 py-1 text-sm rounded border bg-transparent cursor-pointer"
      style="color: {colors.text.primary}; border-color: {colors.ui.border};"
      value={$locale}
      onchange={handleLanguageChange}
      aria-label={$_('header.language')}
    >
      {#each languages as lang}
        <option value={lang.id}>{lang.id.toUpperCase()}</option>
      {/each}
    </select>
  </div>
</header>

<!-- Settings Drawer Overlay -->
{#if settingsOpen}
  <!-- svelte-ignore a11y-click-events-have-key-events -->
  <!-- svelte-ignore a11y-no-static-element-interactions -->
  <div
    class="fixed inset-0 z-50 bg-black/30"
    onclick={closeSettings}
  >
    <!-- Drawer Panel -->
    <!-- svelte-ignore a11y-click-events-have-key-events -->
    <!-- svelte-ignore a11y-no-static-element-interactions -->
    <div
      class="absolute left-0 top-0 h-full w-80 shadow-xl transition-transform"
      style="background-color: {colors.background.secondary};"
      onclick={(e) => e.stopPropagation()}
    >
      <!-- Drawer Header -->
      <div class="flex items-center justify-between p-4 border-b" style="border-color: {colors.ui.border};">
        <h2 class="text-lg font-semibold" style="color: {colors.text.primary};">
          {$_('header.settings')}
        </h2>
        <button
          class="p-2 rounded-lg hover:bg-surface-200 dark:hover:bg-surface-700 transition-colors"
          onclick={closeSettings}
          aria-label="Close"
        >
          <IconX size={20} style="color: {colors.text.primary}" />
        </button>
      </div>

      <!-- Drawer Content -->
      <div class="p-4 space-y-6">
        <!-- Appearance Section -->
        <div>
          <h3 class="text-sm font-semibold mb-3" style="color: {colors.text.primary};">
            {$_('header.appearance')}
          </h3>

          <!-- Dark Mode Toggle -->
          <label class="flex items-center justify-between cursor-pointer">
            <span class="flex items-center gap-2" style="color: {colors.text.primary};">
              {#if $isDark}
                <IconMoon size={18} />
              {:else}
                <IconSun size={18} />
              {/if}
              {$_('header.darkMode')}
            </span>
            <button
              class="relative w-12 h-6 rounded-full transition-colors"
              class:bg-primary-500={$isDark}
              class:bg-surface-400={!$isDark}
              onclick={() => colorScheme.toggle()}
              role="switch"
              aria-checked={$isDark}
            >
              <span
                class="absolute top-1 w-4 h-4 bg-white rounded-full transition-transform"
                class:translate-x-1={!$isDark}
                class:translate-x-7={$isDark}
              ></span>
            </button>
          </label>
        </div>
      </div>
    </div>
  </div>
{/if}
