// frontend/src/components/Widget.tsx
import React from 'react';
import { Card, Text, Group, Stack, Avatar, Badge, Image, Skeleton } from '@mantine/core';
import { IconUser, IconUsers, IconShirtSport } from '@tabler/icons-react';
import type { WidgetData } from '../features/entities/api';

interface WidgetProps {
  /** Widget data from unified entity API */
  data?: WidgetData | null;
  /** Loading state */
  loading?: boolean;
  /** Error message */
  error?: string | null;
  /** Show enhanced details (position, age, etc.) */
  showDetails?: boolean;
  /** Optional className */
  className?: string;
}

/**
 * Widget component - displays entity info card.
 * 
 * Renders widget data from the unified entity API.
 * Supports both basic and enhanced data (photos, positions, etc.)
 */
export default function Widget({ 
  data, 
  loading, 
  error, 
  showDetails = true,
  className 
}: WidgetProps) {
  if (loading) {
    return (
      <Card shadow="sm" padding="lg" radius="md" withBorder className={className}>
        <Group wrap="nowrap" gap="lg">
          <Skeleton height={60} circle />
          <Stack gap={4} style={{ flex: 1 }}>
            <Skeleton height={20} width="70%" />
            <Skeleton height={14} width="50%" />
          </Stack>
        </Group>
      </Card>
    );
  }

  if (error) {
    return (
      <Card shadow="sm" padding="lg" radius="md" withBorder className={className}>
        <Stack align="center" gap="sm">
          <Text size="sm" c="red">{error}</Text>
        </Stack>
      </Card>
    );
  }

  if (!data) {
    return null;
  }

  const isPlayer = data.type === 'player';
  const hasPhoto = data.photo_url || data.logo_url;
  const photoUrl = isPlayer ? data.photo_url : data.logo_url;

  // Build detail badges
  const details: string[] = [];
  if (showDetails) {
    if (data.position) details.push(data.position);
    if (data.age) details.push(`Age ${data.age}`);
    if (data.height) details.push(data.height);
    if (data.conference) details.push(data.conference);
    if (data.division) details.push(data.division);
  }

  return (
    <Card shadow="sm" padding="lg" radius="md" withBorder className={className}>
      <Group wrap="nowrap" gap="lg">
        {/* Photo/Logo or fallback icon */}
        {hasPhoto ? (
          <Image
            src={photoUrl}
            alt={data.display_name}
            w={60}
            h={60}
            radius="xl"
            fit="cover"
            fallbackSrc={undefined}
            onError={(e) => {
              // Hide broken images
              (e.target as HTMLImageElement).style.display = 'none';
            }}
          />
        ) : (
          <Avatar size="lg" radius="xl" color={isPlayer ? 'blue' : 'green'}>
            {isPlayer ? <IconUser size={24} /> : <IconUsers size={24} />}
          </Avatar>
        )}
        
        <Stack gap={4} style={{ flex: 1 }}>
          {/* Name */}
          <Text fw={600} size="lg" lineClamp={1}>
            {data.display_name}
          </Text>
          
          {/* Type badge + subtitle */}
          <Group gap="xs" wrap="wrap">
            <Badge size="sm" variant="light" color={isPlayer ? 'blue' : 'green'}>
              {isPlayer ? 'Player' : 'Team'}
            </Badge>
            {data.subtitle && (
              <Text size="sm" c="dimmed">
                {data.subtitle}
              </Text>
            )}
          </Group>
          
          {/* Enhanced details */}
          {details.length > 0 && (
            <Group gap={6} wrap="wrap" mt={4}>
              {details.map((detail, i) => (
                <Badge 
                  key={i} 
                  size="xs" 
                  variant="outline" 
                  color="gray"
                  leftSection={i === 0 && data.position ? <IconShirtSport size={10} /> : undefined}
                >
                  {detail}
                </Badge>
              ))}
            </Group>
          )}
        </Stack>
      </Group>
    </Card>
  );
}

/**
 * Compact Widget variant - smaller, for lists
 */
export function WidgetCompact({ data, loading }: Pick<WidgetProps, 'data' | 'loading'>) {
  if (loading) {
    return (
      <Group gap="sm">
        <Skeleton height={32} circle />
        <Skeleton height={16} width={100} />
      </Group>
    );
  }

  if (!data) return null;

  const isPlayer = data.type === 'player';
  const photoUrl = isPlayer ? data.photo_url : data.logo_url;

  return (
    <Group gap="sm" wrap="nowrap">
      {photoUrl ? (
        <Image
          src={photoUrl}
          alt={data.display_name}
          w={32}
          h={32}
          radius="xl"
          fit="cover"
        />
      ) : (
        <Avatar size="sm" radius="xl" color={isPlayer ? 'blue' : 'green'}>
          {isPlayer ? <IconUser size={14} /> : <IconUsers size={14} />}
        </Avatar>
      )}
      <Text size="sm" fw={500} lineClamp={1}>
        {data.display_name}
      </Text>
    </Group>
  );
}

// scoracle-svelte/src/lib/components/Widget.svelte
<script lang="ts">
  /**
   * Widget component - displays entity info card.
   * Migrated from React Widget.tsx
   */
  import { IconUser, IconUsers, IconShirtSport } from '@tabler/icons-svelte';
  import type { WidgetData } from '$lib/data/entityApi';

  let { data = null, loading = false, error = null, showDetails = true }: {
    data: WidgetData | null;
    loading?: boolean;
    error?: string | null;
    showDetails?: boolean;
  } = $props();

  let isPlayer = $derived(data?.type === 'player');
  let photoUrl = $derived(isPlayer ? data?.photo_url : data?.logo_url);
  let hasPhoto = $derived(!!photoUrl);

  // Build detail badges
  let details = $derived(showDetails
    ? [
        data?.position,
        data?.age ? `Age ${data.age}` : null,
        data?.height,
        data?.conference,
        data?.division,
      ].filter(Boolean) as string[]
    : []);

  function handleImageError(event: Event) {
    const img = event.target as HTMLImageElement;
    img.style.display = 'none';
  }
</script>

{#if loading}
  <!-- Loading skeleton -->
  <div class="card p-6">
    <div class="flex items-center gap-4">
      <div class="w-16 h-16 rounded-full skeleton" />
      <div class="flex-1 space-y-2">
        <div class="h-5 w-3/4 skeleton rounded" />
        <div class="h-4 w-1/2 skeleton rounded" />
      </div>
    </div>
  </div>
{:else if error}
  <!-- Error state -->
  <div class="card p-6">
    <p class="text-center text-red-500 dark:text-red-400">{error}</p>
  </div>
{:else if data}
  <!-- Widget content -->
  <div class="card p-6">
    <div class="flex items-center gap-4">
      <!-- Photo/Avatar -->
      {#if hasPhoto}
        <img
          src={photoUrl}
          alt={data.display_name}
          class="w-16 h-16 rounded-full object-cover"
          style="background-color: var(--scoracle-bg-tertiary);"
          onerror={handleImageError}
        />
      {:else}
        <div
          class="w-16 h-16 rounded-full flex items-center justify-center"
          class:bg-blue-500={isPlayer}
          class:bg-green-500={!isPlayer}
        >
          {#if isPlayer}
            <IconUser size={24} class="text-white" />
          {:else}
            <IconUsers size={24} class="text-white" />
          {/if}
        </div>
      {/if}

      <!-- Info -->
      <div class="flex-1 min-w-0">
        <h3 class="text-lg font-semibold truncate" style="color: var(--scoracle-text-primary);">
          {data.display_name}
        </h3>

        <div class="flex items-center gap-2 mt-1 flex-wrap">
          <span
            class="px-2 py-0.5 text-xs font-medium rounded-full"
            class:bg-blue-100={isPlayer}
            class:text-blue-700={isPlayer}
            class:dark:bg-blue-900={isPlayer}
            class:dark:text-blue-300={isPlayer}
            class:bg-green-100={!isPlayer}
            class:text-green-700={!isPlayer}
            class:dark:bg-green-900={!isPlayer}
            class:dark:text-green-300={!isPlayer}
          >
            {isPlayer ? 'Player' : 'Team'}
          </span>
          {#if data.subtitle}
            <span class="text-sm" style="color: var(--scoracle-text-secondary);">
              {data.subtitle}
            </span>
          {/if}
        </div>

        {#if details.length > 0}
          <div class="flex flex-wrap gap-1.5 mt-2">
            {#each details as detail, i}
              <span
                class="px-2 py-0.5 text-xs rounded-full border flex items-center gap-1"
                style="border-color: var(--scoracle-ui-border); color: var(--scoracle-text-secondary);"
              >
                {#if i === 0 && data.position}
                  <IconShirtSport size={10} />
                {/if}
                {detail}
              </span>
            {/each}
          </div>
        {/if}
      </div>
    </div>
  </div>
{/if}
